"""init

Revision ID: 868e4f98b224
Revises: 
Create Date: 2026-05-10 11:10:10.569376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '868e4f98b224'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('client_ip', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_id'), 'submission', ['id'], unique=False)
    op.add_column('content_log', sa.Column('submission_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'content_log', 'submission', ['submission_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content_log', type_='foreignkey')
    op.drop_column('content_log', 'submission_id')
    op.drop_index(op.f('ix_submission_id'), table_name='submission')
    op.drop_table('submission')
    # ### end Alembic commands ###
